server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/element_ui_demo?characterEncoding=utf8&useSSL=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent-output: true

logging:
  level:
    root: info
